name: Update proxy.pac file

on:
  push:

  schedule:
    - cron: "0 0 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run update script
        run: |
          update-proxy-pac.sh

      - name: Commit files
        run: |
          git config --local user.name "MrKsey"
          git config --local user.email "17622530+MrKsey@users.noreply.github.com"
          git add .
          git commit -am "$(date +%d.%m.%Y) Update proxy.pac file"
          git push
