name: Update proxy.pac file

on:
  push:
    paths-ignore:
      - 'README.md'

  schedule:
    - cron: "0 2 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run update script
        run: |
          sh ./update-proxy-pac.sh

      - name: Commit files
        run: |
          git config --local user.name "MrKsey"
          git config --local user.email "17622530+MrKsey@users.noreply.github.com"
          git add .
          git commit -am "$(date): updated proxy.pac file"
          git push
